ksonnet/ksonnet

cmd/root.go
metadata/environment.go
metadata/environment_test.go
metadata/interface.go
metadata/manager.go
metadata/manager_test.go

**SEE [PR](https://github.com/ksonnet/kubecfg/pull/167) FROM OLD REPOSITORY FOR EXISTING COMMENTS**
Implements part of #6 . This PR does a few things:
1. Hide environment metadata details that we do not want users modifying in a `.metadata` folder (`k.libsonnet`, `k8s.libsonnet`, `swagger.json`)
2. Generate base.libsonnet:
base.libsonnet is a generated file that exists at the root of the
environments directory. This file is generated for all ksonnet projects.
The main goal of this file is to import all components in the components
directory, so that environments are able to easily extend / override any
one of these components in a modular structure.
3. Generate the override file:
Generate an "<env-name>.jsonnet" file when an environment is created.
The goal of this file is to allow users …

Environment base.libsonnet and overrides

---

cmd/apply.go
cmd/delete.go
cmd/diff.go
cmd/env.go
cmd/init.go
cmd/root.go
cmd/update.go
metadata/environment.go
metadata/environment_test.go
metadata/interface.go
metadata/manager.go
metadata/manager_test.go
pkg/kubecfg/apply.go
pkg/kubecfg/delete.go
pkg/kubecfg/diff.go
pkg/kubecfg/env.go
pkg/kubecfg/init.go

**SEE [PR](https://github.com/ksonnet/kubecfg/pull/161) FROM OLD REPOSITORY FOR EXISTING COMMENTS**
**Fixes #9**
Environments currently have the concept of a server URI, but it is
ambiguous which cluster namespace to use.
This commit will introduce the concept of namespaces to the env
commands.
For example,
`kubecfg env add staging http://mock-staging-uri \
--namespace=staging-namespace`
`kubecfg env set staging --namespace=staging-namespace`
The default environment will use the namespace of the default context.
This commit will also update commands that take the <env> arg such as
`apply` to make use of the env namespace, if specified.

Introduce namespace to environments

---

README.md

ksonnet.next isn't released yet. This message remained as a port from
the original README file in the kubecfg project.

Remove link to releases page

---

cmd/env.go
cmd/root.go

Wait for #24 to merge before review.
Fixes #3
`ks env set foo --namespace=""` and `ks env add foo` will now both set the
namespace to 'default' in the environment's spec.json file.

 Set env namespace to default when namespace not provided

---

cmd/diff.go
cmd/root.go
cmd/root_test.go
pkg/kubecfg/apply.go
pkg/kubecfg/diff.go
utils/meta.go

**SEE [PR](https://github.com/ksonnet/kubecfg/pull/167) FROM OLD REPOSITORY FOR EXISTING COMMENTS**
**Fixes: #7**
First look at supporting diff between two environments.
This PR will support changes such as
`ks diff local:dev local:prod`,
`ks diff remote:dev remote:prod`, or
`ks diff local:dev remote:dev`. 
The last is the same as the existing diff functionality `ks diff dev` (which is still supported).

Support `diff`ing between two environments

---

cmd/prototype.go

Also fixes #46 .
You will note that in the code change, I removed the command name from the error messages. This is because of
1. Shared logic between the two command names
2. Since we're printing the usage, I didn't find having the command name in the error message itself providing any additional help.

Add alias 'ks generate' for 'ks prototype use'

---

cmd/prototype.go
metadata/app/schema.go
metadata/interface.go
metadata/registry.go
metadata/registry_managers.go
prototype/specification.go

Just a note, the prototype comment parsing comes out of the ksonnet/parts doc gen code, so this is not actually new. We will eventually pull that out and vendor this into that project.

Add ability to retrieve prototypes from vendor/

---

cmd/diff.go
cmd/root.go

This fixes the bug where objects weren't being deployed to the cluster
specified by the environment. This bug occurred because overrides (ex:
cluster, namespace) were being lost because we weren't applying the
changes to the correct override object. To fix this, we needed to pass
the overrides by reference.
Fixes #53

Pass context & overrides by reference when initiating client

---

cmd/diff.go
cmd/root.go
metadata/interface.go
metadata/manager.go
metadata/manager_test.go

This resolves the first half of #68. When we `generate` using a
prototype from a vendored dependency, it often results in a compilation
error when we `apply`, because these prototypes usually depend on code
that exists in the dependency, and `vendor/` is not a part of the
Jsonnet search path.
This commit resolves this problem by adding it to the search path.

Add `vendor/` to Jsonnet paths

---

cmd/prototype.go
cmd/root.go
cmd/root_test.go
metadata/params/params.go
metadata/params/params_test.go
utils/strings.go
utils/strings_test.go

Currently, if a component name contains a special character, ex:
foo-bar, this translates to the jsonnet identifier: foo-bar, which is
invalid syntax.
This change will quote component names where there are special
characters.
Fixes #51

Jsonnet handling of component names with special characters

---

metadata/app/schema.go
metadata/manager.go
metadata/parts/schema.go
metadata/registry.go
metadata/registry/schema.go
metadata/registry_managers.go
prototype/interface.go

Fixes #48.
Currently the structs `app.Spec`, `registry.Spec`, and `parts.Spec` are
all serialized and deserialized using JSON instead of YAML.
This commit will resolve this issue.

De/serialize specification objects with YAML

---

prototype/specification.go

Was using the wrong index. PTAL @hausdorff 

[bug fix] Fix optionalParam defaults

---

pkg/kubecfg/param.go

Foreground colors were causing conflicts with user's terminal colors.
i.e. Black text would show as invisible for users with a black terminal
background.
Fixes #81

Use background colors for param diff

---

cmd/root.go

Currently, ExtCodes are only provided when the 'env' flag is present in
commands. The result is errors occuring when we run commands such as `ks
show default -f components/guestbook-ui.jsonnet`, where the params
ExtVar is needed. This commit fixes that scenario.
Fixes #85

Provide access to ExtCodes when the '-f' flag is provided

---

metadata/params/params.go
metadata/params/params_test.go
utils/strings.go

A bug existed where if `param set` was called for the same param twice,
a duplicate entry was created for the component. This only occured where
the component name contained a special character.
Fixes #80

Fix bug for duplicate environment params

---

cmd/prototype.go

When `generate` was first implemented, we made a conscious decision to
not include the `--help` flag, so that we would not accidentally break
templates with a parameter called `help`.
But, this is unintuitive for users who want to use the `--help` flag, so
in this commit we will print the help message if (1) there is a single
command argument, and (2) it is either `--help` or `-h`.
Fixes #21.

🆘 Add `--help` flag to `generate` and `prototype use`

---

cmd/prototype.go
docs/cli-reference/ks_generate.md
docs/cli-reference/ks_prototype_preview.md
docs/cli-reference/ks_prototype_use.md

fixes #64
Remove YAML, JSON examples from prototype command descriptions.
Fixes a bug where non-Jsonnet prototypes were expanded using incorrect parser.

YAML, JSON handling for prototype commands

---

cmd/root.go
metadata/environment.go
utils/strings.go
utils/strings_test.go

As part of the environments feature, we want to be able to deploy to a
specific cluster given the environment's URI. We cross-check against
kubecfg for this URI's location. For fail-safe comparison, we probably
want to normalize these URIs.

Normalize environment server URL

---

cmd/root.go

In line 161 of `root.go`, we're failing to check whether a cluster in
the $KUBECONFIG clusters array exists before using it. This will cause a
`nil` dereference error.

Fix `nil` dereference error in #129

---

metadata/environment.go
metadata/environment_test.go
metadata/manager.go
metadata/manager_test.go

Currently, creating a `dev` environment will create a file
`dev.jsonnet`. Creating a `prod` environment will create a file
`prod.jsonnet`. This is a little more complex and prone to error than it
needs to be, especially when we are renaming environments. It will also
make this file easier to refer to in documentation if we give the file a
static name -- `main.jsonnet`.
Fixes #77 
--
Also, support renaming of environments to parent and child directories.
Fixes #76

Rename <env>.jsonnet file to main.jsonnet

---

cmd/init.go
cmd/root.go
metadata/manager.go
pkg/kubecfg/init.go

Fixes #115 
- Add message:  Creating a new app 'foo' at path '/path/to/foo'
- On success, add message:  ksonnet app successfully created! Next, try
creating a component with `ks generate`
- On failure, provide suggestions for the user.
- Make note that the context is retrieved from the kubeconfig file at
the environment variable $KUBECONFIG

Improve logging for init

---

README.md
docs/concepts.md
prototype/prototype_test.go
prototype/systemPrototypes.go

@hausdorff @jessicayuen PTAL
If it's clearer, I can split this into two PRs, but changes are:
* Changes to README based on Ruben and Joe's feedback
* Rename `deployment-exposed-with-service` prototype to `deployed-service`
Intended to fix https://github.com/ksonnet/ksonnet/issues/134 and https://github.com/ksonnet/ksonnet/issues/118

[docs][prototypes] Rename 'deployment-exposed-with-service' and address README feedback

---

cmd/diff.go

Output usage and return when no command args are provided for `ks diff`.
Fixes #158

Fix segfault for ks diff

---

metadata/environment.go
metadata/environment_test.go

Currently absolute paths are being used for jsonnet imports. This makes
it difficult to share the files across different systems.
Fixes #149

Use relative paths on jsonnet imports

---

cmd/pkg.go
metadata/interface.go
metadata/registry_managers.go

Fixes #151 
Currently, if a version is not provided to the following `pkg install`
command
`../ks pkg install incubator/redis`
, the following error will occur:
`ERROR GET
https://api.github.com/repos/ksonnet/parts/commits/incubator/redis: 404
Not Found []`
This commit will pull in the latest package from master where the
version is not specified.
Also set the default repository ref to 'master' instead of 'test-reg'.

pkg install: Use 'master' as refSpec where version isn't provided

---

cmd/env.go
cmd/param.go
cmd/pkg.go
cmd/prototype.go
cmd/registry.go

Currently, commands such as `ks env non-existent-subcommand` will output
an error `Command 'env' requires a subcommand`.
This is not helpful since the user may assume there is the subcommand
'non-existent-subcommand'. This commit will clarify the error messages
in this scenario.
Fixes #140

 Clarify errors for commands requiring subcommands

---

cmd/env.go
cmd/init.go
cmd/root.go

If the namespace is not provided in the target kubeconfig context, use
'default'.
Also squashes a bug where the namespace, server flags may have been
ignored during init.
Fixes #116, #49

Initialize namespace to 'default' if not specified

---

cmd/version.go

Trivial change. Partially address #170

Rename 'kubecfg version' to 'ksonnet version'

---

.gitignore
cmd/prototype.go

Use component name for param name if name parameter is omitted
In general, prototypes have a name param. To reduce duplication, use the component name for the name param if the name parameter is omitted. This will turn :
```
ks prototype use deployed-service guestbook-ui \
--name guestbook-ui \
--image alpinejay/dns-single-redis-guestbook:1.0 \
--type LoadBalancer
```
into
```
ks prototype use deployed-service guestbook-ui \
--image alpinejay/dns-single-redis-guestbook:1.0 \
--type LoadBalancer
```
as the `--name` parameter will be inferred. If the operator wishes the name to be different, they can supply the name parameter:
```
ks prototype use deployed-service guestbook-ui \
--name fancy-stuff \
--image alpinejay/dns-single-redis-guestbook:1.0 \
--type LoadBalancer
```
This PR also adds …

Generated component name is optional

---

cmd/env.go

Fixes #172 
There is a bug where the `default` environment was not using the
`--namespace` flag, even when set.
This is due to a path of execution error where `ns` is overriden during
`resolveContext`, so it will never be empty -- resulting in a check
failure in line 345.

Fix for namespace flag not registering on init

---

README.md

Since `ks diff` output is not very clean or user-friendly, let's show `ks param list` instead.
@jessicayuen PTAL

[docs] Remove diff command in example

---

cmd/prototype.go
docs/cli-reference/ks.md
docs/cli-reference/ks_generate.md
docs/cli-reference/ks_prototype.md
docs/cli-reference/ks_prototype_describe.md
docs/cli-reference/ks_prototype_list.md
docs/cli-reference/ks_prototype_preview.md
docs/cli-reference/ks_prototype_search.md
docs/cli-reference/ks_prototype_use.md

@jessicayuen PTAL!
I checked that all the alignments look ok in my terminal. Did some formatting hacks to make different sections of the docs clearer.
Let me know what you think! Am going to try to replicate this across the other commands unless otherwise instructed.

[docs] Fix CLI reference for `ks-prototype`

---

prototype/specification.go

Turns out this is actually required for https://github.com/ksonnet/ksonnet/issues/182.
This code needs to be present for https://github.com/ksonnet/parts/pull/51 to actually do anything.
I tested this locally (by changing the registry reference for `incubator`) and it works:
@jessicayuen PTAL thanks!!

Parse short description for prototypes

---

README.md
cmd/prototype.go
docs/cli-reference/ks_generate.md
docs/cli-reference/ks_prototype_use.md
docs/troubleshooting.md

@jessicayuen @bryanl PTAL thanks!
This PR addresses part of https://github.com/ksonnet/ksonnet/issues/194.

[docs] Remove (now optional) `--name` syntax from `ks generate` commands

---

cmd/pkg.go
docs/cli-reference/ks_pkg_install.md

Currently the package name is listed before the registry name in `pkg
list`. This is inconsistent with the order of `pkg install` which is of
the format `<registry>/<package>`. This change will display the registry
name before the package name in `pkg list`.
Fixes #195 

Reverse name, registry columns for pkg list

---

metadata/environment.go

It is possible for the walk function to be called with err set

Check error while enumerating environments

---

cmd/root.go
metadata/params/params.go
metadata/params/params_test.go
utils/strings.go
utils/strings_test.go

**Fixes #214**
Currently, if we run `param set guestbook-ui foo-bar x`,
The jsonnet snippet will write: `foo-bar: "x"`.
However, this is incorrect jsonnet syntax. This commit will fix this
issue, to instead write `"foo-bar": "x"`.
Also updates the `Get...` Param functions to return non-quoted
identifiers for prettier display.

Accurately read/write non-ASCII param identifiers

---

cmd/registry.go
docs/cli-reference/ks_registry.md
docs/cli-reference/ks_registry_add.md
metadata/registry.go
pkg/kubecfg/registry.go

Fixes #226
Currently users are unable to add their own registries through the CLI.
This limits them to a small subset of prototypes found in the default
incubator registry.
This commit will add the command `ks registry add`, that allows users to
add registries supporting the `github` protocol.
It will be of the form `ks registry add <registry-name> <registry-uri>
[--version]`. If a version is not specified, `latest` will be used.

Implement command `ks registry add`

---

metadata/registry_managers.go
metadata/registry_test.go

When a user adds a registry (e.g., through a command like `ks registry
add`, or implicitly through `ks init`) we must parse a URI pointing at
registry hosted on github.com, since we currently only support the
`"github"` protocol.
This logic is somewhat complex, since we must
1. infer the location of a `registry.yaml` file given the URI, and
2. accept and parse a broad set of URIs a user might provide.
For example, consider the following valid URIs, and what we do to infer
the location of the `registry.yaml` file that specifies a registry:
URIs with an explicit `registry.yaml`:
github.com/exampleOrg/exampleRepo/blob/master/registry.yaml
github.com/exampleOrg/exampleRepo/blob/master/incubator/registry.yaml
URIs with an implicit `registry.yaml`:
github.com/exampleOrg/exampleRepo/ …

Test all branches of GH URI-parsing code

---

cmd/registry.go
docs/cli-reference/ks_registry_add.md
docs/concepts.md

@bryanl i know this is after you cut the release, so the edits to the CLI `--help` won't make it into the binary. not a *huge* issue though, at the very least, the docs site will be able to leverage these updates.

[docs] Update docs for 0.8.0

---

Makefile

Allows you to run `VERSION=v0.x.0 KS_BIN=ks-custom make ks`. This is useful if building ks in a docker container.

Allow make file to generate ks bin with custom version and name

---

README.md
design/roadmap.md
docs/README.md

Intended to address https://github.com/ksonnet/ksonnet/issues/207 (at least partially).
Unlike with [Contour's design docs](https://github.com/heptio/contour/tree/master/design), I opted to nest these inside of `docs/`. I think that this sort of organization is actually simpler because it's one less top-level directory to check, but if anyone feels strongly about that I'm happy to discuss and change.
This also might not be the proper structure/format for a roadmap (it seems to overlap a fair amount with stuff in the [issues](https://github.com/ksonnet/ksonnet/issues)?), but I'm hoping that even if we don't merge this in, it proves helpful in the planning/prioritization discussion tomorrow.
cc @jessicayuen @hausdorff @bryanl 

[docs] Add roadmap

---

cmd/component.go
docs/cli-reference/ks.md
docs/cli-reference/ks_component.md
docs/cli-reference/ks_component_list.md
metadata/component.go
metadata/component_test.go
metadata/interface.go
metadata/manager.go
metadata/manager_test.go
pkg/kubecfg/component.go
pkg/kubecfg/component_test.go

Fixes #242 
This adds a high level 'component' command and a 'component list'
command. 'component list' will pretty print all the components in
ksonnet application directory.
To accomplish this, an API is added to the metadata manager that returns
all components. Components are the individual files in /components, with
the path extension trimmed.
@abiogenesis-now Going to add this to your radar since you may want to update the docs once this is merged! The command docs for this command are currently very trivial.

Add command 'component list'

---

metadata/registry.go

Fixes #269 
Consider the scenario where the user has two registries 'incubator', and
'incubatorXYZ' pointing to the same repository.
It might be confusing why running `ks pkg install incubatorXYZ/mysql`
fails if they ran `ks pkg install incubator/mysql` previously.
This is a small change to help users resolve that scenario by passing
the `--name` flag on install.

Clarify error message for duplicate packages on install

---

design/proposals/explicit-environment-metadata.md

Proposal for explicit environment metadata; allowing environment metadata (such as namespace, server URI) to be reference-able at the component and prototype manifest level.
Attempts to address #222

Design proposal: explicit environment metadata

---

docs/generate/update-generated-docs.sh

Darwin (Mac OS systems) does not ship with `realpath` by default
So this removes the `realpath` reference so `make` works out of the box

Removing realpath

---

cmd/diff.go
cmd/prototype.go
cmd/root.go
metadata/interface.go
metadata/manager.go
metadata/manager_test.go
prototype/snippet/jsonnet/snippet.go
prototype/snippet/jsonnet/snippet_test.go

Partially implements the proposal [here](https://github.com/ksonnet/ksonnet/blob/master/design/proposals/explicit-environment-metadata.md).
Version 2 of prototypes in the parts library that follow the historical model of hard-coded namespaces will be updated subsequently. This change does not break existing prototypes.
Fixes #222

Implement explicit env metadata

---

Makefile
cmd/version.go
main.go

Using `Version()` as a string leaves a preprocessed version tag in the
ksonnet version. Construct a new version using the `Major` and `Minor`
fields.
Re: #250

Construct apimachinery version

---

cmd/component.go
docs/cli-reference/ks_component.md
docs/cli-reference/ks_component_rm.md
metadata/component.go
metadata/component_test.go
metadata/interface.go
metadata/params/interface.go
metadata/params/params.go
metadata/params/params_test.go
pkg/kubecfg/component.go

Fixes #243 
Introduce `ks component rm <component>`. This functionality will:
1. Delete the component file from components/. This is determined by the
component file name. If there exists two files with the same name but
different file  extensions, we will error out.
2. Remove component references. This currently implies removing all
component referenes in the component/params.libsonnet file and the
environment-specific params.libsonnet files.

Add remove component functionality

---

docs/concepts.md
docs/troubleshooting.md

Minor doc changes to do the following:
* Clarify that prototypes are more like *examples*, rather than like Helm's plug-and-play charts
* Instructions to cover https://github.com/ksonnet/ksonnet/issues/298#issuecomment-360531855 until new binaries are released for 0.9.0.
@bryanl @jessicayuen PTAL thanks!

[docs] Clarify prototypes + add troubleshooting issue

---

metadata/app/schema.go
metadata/app/schema_test.go
metadata/component.go
metadata/component_test.go
metadata/manager.go
metadata/manager_test.go

- Add EnvironmentSpec to app.yaml
- Move the component param logic from metadata/manager.go into metadata/component.go
Partially implements #292

Add interface for Environment Spec

---

cmd/apply.go
metadata/environment.go
metadata/interface.go

This is a temporary piece of code that should be removed after 1.0.0.
This warning exists to tell users that are using ks < 0.9.0 with the
dated environments model (contains the 'spec.json' file), to migrate to
the newer 'app.yaml' model.

Add warning for running deprecated ks app against ks >= 0.9.0

---

client/client.go
cmd/root.go
integration/integration_suite_test.go
metadata/app/schema.go
metadata/app/schema_test.go
metadata/environment.go
metadata/environment_test.go
pkg/kubecfg/env.go
testdata/testapp/app.yaml

Currently the app.yaml spec takes a list of destinations. The change
exists to anticipate support for an environment supporting multiple
clusters or "destinations". The problem is, while the use case makes
sense for `apply`, and `delete`, it becomes ambiguous which cluster is
being referred to during commands such as `diff`. We've considered
specifying a cluster during a `diff`, however, ks currently doesn't have
a notion of a cluster identity. This change is to update the app.yaml to
take a single destination to more accurately represent the state of
things.

App spec to take a single destination

---

cmd/diff.go
cmd/root.go
integration/fixtures/sampleapp/environments/default/main.jsonnet
metadata/environment.go
metadata/environment_test.go
metadata/interface.go
metadata/manager.go
metadata/manager_test.go

Fixes #321 
There exists a bug in the reference path of base.libsonnet for nested
environment directories. We are referencing a hardcoded import
"../base.libsonnet". The works for top level environment directories but
obviously does not work for nested directories.
This commit will add the environments directory as a global lib path.

Fix bug with invalid base.libsonnet import path

---

pkg/kubecfg/param.go
pkg/kubecfg/param_test.go

Fixes #311 
There currently exists a discrepency between the param types expected
from:
1. The parts library and in generate / prototype use
2. ks param set
ks param set will set boolean types as jsonnet boolean types, however,
prototypes will set boolean types as strings (i.e. in quotes). This
change will make it such that ks param sets boolean types as strings.
The reason we're not setting booleans in both model is because that will
require a better dependency story around ksonnet/parts first.

Set param boolean types as strings

---

client/client.go
cmd/env.go
cmd/init.go
docs/cli-reference/ks_init.md

Currently the Kubernetes API version used is defaulted to 1.7.0 if the
--api-spec flag is not populated. This change will attempt to retrieve
the swagger.json version from the server instead.
Note: This is currently a very trivial attempt at retrieving it from the
server. Efforts will be made later to support TLS / Certificates.

Resolve api spec based on swagger version

---

Gopkg.lock
cmd/apply.go
metadata/environment.go
metadata/interface.go
testdata/testapp/environments/default/spec.json

Currently the warning is only displayed on 'apply'. Other commands
should also show this warning. Logic should also be handled internally
instead of being exposed at the interface level.

Fix the execution paths for the 0.8 > 0.9 migration warning

---

utils/meta.go
utils/meta_test.go

Fixes #342
We currently attempt to parse the server version from the Major / Minor
version provided by client-go's ServerVersion object. It is not always
the case that these fields are populated; and is more accurate to use
the GitVersion.

Parse server version from GitVersion

---

env/rename.go
env/rename_test.go
metadata/app/app.go
metadata/app/app001.go
metadata/app/app001_test.go
metadata/app/app010.go
metadata/app/app010_test.go
metadata/app/helpers_test.go
metadata/app/mocks/App.go
metadata/app/testdata/app010_app.yaml
metadata/app/testdata/main.jsonnet

When renaming environments, rename env in config file

bug: 0.1.0 apps don't rename envs in config

---

metadata/app/app010.go
metadata/app/app010_test.go

when updating an app env with no k8s spec flag,
don't attempt to check the lib path

update app env with no k8s spec flag

---

cmd/root.go

ksonnet plugins scrub the environment available to a plugin. Add `HOME`,
so client-go can find the files it is looking for.

Add HOME to plugin env

---

cmd/root.go
metadata/app/app.go
metadata/app/app_test.go
metadata/app/schema.go

Allow ks command to work in any subdirectory of a ksonnet app. If
`app.yaml` is not found in the current directory, look for it in parent
directories.

Allow `ks` command to work anywhere in app

---

metadata/params/params.go

Adds support for `ast.ApplyBrace` when setting parameters.
Fixes #381 

handle jsonnet ast.ApplyBrace in env files

---

component/jsonnet.go

When max stack traces exceeded, often there is no enough user-written code seen to identify source of the loop. this change makes it it print more stack frames

Print more stack frames on infinite loops

---

client/client.go

When using a kubeconfig file from an environment variable, supplied by a
command line argument, or the default location, print the location of
the file.
Fixes #287

Print location of kubeconfig

---

Gopkg.lock
Gopkg.toml
vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/nodemaker/nodemaker.go

Running:
```
ks param set my-service envs '[{"name": "value1"},{"name": "value2"}]'
```
Produces the following in params.libsonnet
```javascript
{
components: {
"my-service": {
envs: [{
name: "value1",
},{
name: "value2",
}],
},
},
}
```
Fixes #448

Set maps in arrays from cli

---

pkg/env/env.go

enviroment `main.jsonnet` files updated the path of the import of
`base.libsonnet` to remove the relative bits because you can't assume
that the environment root is directly off the root. This breaks older
applications. The fix is to add the environment path to the jpath.
Fixes #493

Add environment path to jpath for relative imports

---

pkg/util/jsonnet/object.go
pkg/util/jsonnet/object_test.go

When setting parameters, if the value starts with a leading 0 and is
not a float, consider it to be a string.
e.g.:
00: string
0.1: float
0: int
#492

decode string with leading 0 as string

---

pkg/env/data.go

import is not needed if it isn't being used
Fixes #514

Disable environment ksonnet-lib import by default

---

pkg/util/jsonnet/vm.go
pkg/util/jsonnet/vm_test.go

re-enables native funcs for components:
* parseYaml
* parseJson
* regexMatch
* regexSubst
* escapeStringRegex
Fixes #508

Make native funcs available for components

---

pkg/util/jsonnet/object.go
pkg/util/jsonnet/object_test.go

If param set float fails, use string

---

pkg/cluster/apply.go
pkg/cluster/apply_test.go

When applying objects to cluster, annotate them with
`ksonnet.io/managed`. This annotation is an array which includes a
JSONPath to all to updated fields.
If a field as an array and contains an object with a name field, create
a selector which defined a route to that field.

Annotate updated fields when apply objects

---

pkg/app/base_app.go
pkg/app/base_app_test.go
pkg/app/encoder.go
pkg/app/override.go
pkg/app/override_test.go
pkg/app/schema.go
pkg/app/testdata/add-registry-override-invalid.yaml
pkg/app/testdata/write-override.yaml

Adds identifying information to app override configuration
example:
```
apiVersion: 0.1.0
kind: ksonnet.io/app-override
registries:
container:
protocol: fs
uri: ../../../../../../Development/heptio/ksonnet-container
```
Fixes #513

Add apiVersion/kind to app.override.yaml

---

pkg/actions/param_set.go
pkg/actions/param_set_test.go

Checks to see if there a component before trying to set the component.
Fixes #564

Panic when setting non-existing component param

---

docs/cli-reference/ks_pkg_list.md
pkg/actions/actions.go
pkg/actions/pkg_list.go
pkg/actions/pkg_list_test.go
pkg/actions/testdata/pkg/list/installed.txt
pkg/clicmd/flags.go
pkg/clicmd/pkg_list.go
pkg/clicmd/pkg_list_test.go

Adds a new flag to `pkg list` that only lists installed packages.

Add `--installed` flag to pkg list

---

pkg/actions/prototype_preview.go
pkg/actions/prototype_preview_test.go
pkg/actions/prototype_use.go
pkg/actions/prototype_use_test.go
pkg/component/locator_test.go
pkg/prototype/flags.go
pkg/prototype/flags_test.go

Prototypes now have builtin parameters (module)
If a prototype defined a parameter named module, recover
the panic that will occur and present an error instead.
Fixes #607

Recover from panic when redifining prototype param

---

docs/concepts.md

Black friday vs kramdown difference: black friday requires a newline after text to start a bullet list.
Might be worth moving this document to the website repo since it is not autogenerated.

Add newline prior to lists

---

pkg/clicmd/env.go
pkg/clicmd/env_add.go
pkg/clicmd/init.go

Continuing to remove reliance on globals

Remove global client config for init

---

docs/cli-reference/ks_generate.md
docs/cli-reference/ks_prototype_preview.md
docs/cli-reference/ks_prototype_use.md
pkg/actions/prototype_preview.go
pkg/actions/prototype_use.go
pkg/clicmd/prototype_preview.go
pkg/clicmd/prototype_use.go
pkg/prototype/flags.go
pkg/prototype/flags_test.go
pkg/prototype/values_file.go
pkg/prototype/values_file_test.go

This change introduces a values file to be used when setting prototype
values for the use and preview commands.
The format of the file is Jsonnet that returns an object.
Notes:
* if values are added to the file and aren't consumed by prototype, they are ignored.
Fixes #550 

Use values file for prototype use/preview

---

pkg/actions/pkg_list.go
pkg/actions/pkg_list_test.go
pkg/actions/testdata/pkg/list/installed.txt
pkg/actions/testdata/pkg/list/output.txt

```
➜  ksapp2 ks pkg list
REGISTRY  NAME      VERSION INSTALLED
========  ====      ======= =========
incubator apache    master
incubator efk       master
incubator mariadb   master
incubator memcached master
incubator mongodb   master
incubator mysql     master
incubator nginx     master
incubator node      master
incubator postgres  master
incubator redis     master
incubator tomcat    master
```
And after installing a package:
```
➜  ksapp2 ks pkg list --installed
REGISTRY  NAME   VERSION INSTALLED
========  ====   ======= =========
incubator apache master  *
```
#626

When listing packages, include version

---

pkg/client/client.go
pkg/client/client_test.go

instead of using OpenAPISchema for version because openshift stores its
own version data in Info.Version
this only addresses the app init section - there are other places where version info could be gathered for environments that will need to be addressed as well. before i head down that road i'm pushing this to check and see if this is the right direction to move in - which is why it's WIP right now.
related to #427

Shift to ServerVersion call to get version

---

pkg/actions/upgrade.go
pkg/actions/upgrade_test.go
pkg/app/app.go
pkg/app/app001.go
pkg/app/app001_test.go
pkg/app/app010.go
pkg/app/app010_test.go
pkg/app/mocks/App.go
pkg/clicmd/root.go
pkg/pkg/local.go
pkg/upgrade/testdata/app010_app.yaml
pkg/upgrade/testdata/main.jsonnet
pkg/upgrade/testdata/packages/mysql/parts.yaml
pkg/upgrade/upgrade.go
pkg/upgrade/upgrade001.go
pkg/upgrade/upgrade010.go
pkg/upgrade/upgrade010_test.go

Example:
`vendor/<registry>/<pkg>` -> `vendor/<registry>/<pkg>@<version>`
Closes #663

ks upgrade relocates vendored packages to versioned paths

---

pkg/actions/module_create.go
pkg/component/manager.go
pkg/component/module.go
pkg/component/module_test.go

Allow creation of module `a` when module `a.b` previously exists.
Changes module finding to look for `params.libsonnet` instead of
the module directory.
Fixes #675

Create module when child exists

---

pkg/params/rice-box.go
pkg/params/scripts/params_for_module.libsonnet
pkg/params/testdata/build_env_params/input.jsonnet
pkg/params/testdata/build_env_params/module.jsonnet

There is a case where empty parameter values could get dropped
from environment parameters
In
```
{
components: {
component: {
values: {}
}
}
}
```
component.values would be dropped because it contained an
empty object.

Don't drop empty objects/arrays in env params

---

pkg/cluster/apply.go
pkg/cluster/apply_test.go

Add conditionals for object tagging and upserting.
#615

Don't change cluster in apply dry run modified

---

hacks/ks-verify-helm.rb
pkg/env/env.go
pkg/helm/chart.go
pkg/helm/renderer.go
pkg/helm/renderer_test.go
pkg/util/version/sort.go
pkg/util/version/sort_test.go
pkg/util/version/version.go
pkg/util/version/version_test.go

Fixing regressions in the ksonnet helm integration:
* handle chart versions like `v0.1.3` when finding the latest version
* make kubernetes cluster version available to charts
* add ks helm repository verification tool

Helm chart verification

---

pkg/pkg/helm.go
pkg/pkg/local.go
pkg/prototype/prototype.go
pkg/registry/package_manager.go
pkg/registry/package_manager_test.go
pkg/util/version/sort.go
pkg/util/version/sort_test.go
pkg/util/version/version.go
pkg/util/version/version_test.go

Closes #713
To exercise:
```
ks init test-713 && cd test-713/
ks env add stage
ks pkg install --env stage incubator/nginx
ks prototype list
ks prototype preview io.ksonnet.pkg.nginx-simple --name myNginx
ks prototype use io.ksonnet.pkg.nginx-simple myNginx
```

Support prototype resolution from environment-scoped packages

---

pkg/helm/renderer.go
pkg/helm/renderer_test.go

Fixes #723 
This change makes the current environment's namespace available to the helm rendering engine.

Set Kubernetes namespace in helm engine options

---

pkg/actions/param_delete.go
pkg/actions/param_delete_test.go

Closes #690 
Should not affect global path e.g.
```
ks param set replicas 4 --env default
ks param delete replicas --env default
```
Addresses case where `ks param delete <string>` where component name or param key is missing.

Check component exists prior to delete in local

---

docs/cli-reference/ks_pkg_install.md
pkg/actions/actions.go
pkg/actions/pkg_install.go
pkg/actions/pkg_install_test.go
pkg/clicmd/flags.go
pkg/clicmd/pkg_install.go
pkg/clicmd/pkg_install_test.go
pkg/registry/cache.go
pkg/registry/cache_test.go

This feature is added to allow two versions of a package to be
installed. (e.g. having multiple versions of a helm chart installed)
cc: @GuessWhoSamFoo 

All user to force install package with --force

---

pkg/actions/pkg_list.go
pkg/actions/pkg_list_test.go
pkg/actions/registry_describe_test.go
pkg/actions/testdata/pkg/list/installed.txt
pkg/actions/testdata/pkg/list/output.json
pkg/actions/testdata/pkg/list/output.txt
pkg/pkg/local.go
pkg/pkg/pkg.go
pkg/registry/add_test.go
pkg/registry/fs_test.go
pkg/registry/github.go
pkg/registry/github_test.go
pkg/registry/helm.go
pkg/registry/helm_test.go
pkg/registry/mocks/PackageManager.go
pkg/registry/package_manager.go
pkg/registry/package_manager_test.go
pkg/registry/schema.go
pkg/registry/schema_test.go
pkg/registry/testdata/registry-old-with-gitversion.yaml
pkg/registry/testdata/registry.yaml

Part of #626
* Add RemotePackages method to package manager
* pkg list uses PackageManger rather than App
* Packages from GitHub registry inherit version from the registry,
rather than that specified in registry.yaml.
* Rename registry.LibaryConfig -> LibraryConfig
```
ksdev init 626-pkg-list && cd 626-pkg-list
ksdev pkg list
ksdev env add stage
ksdev pkg install --env stage incubator/nginx@58ea0ff91474d488ea50829042b45fe962bd2fa3
ksdev pkg install --env stage incubator/nginx@58ea0ff91474d488ea50829042b45fe962bd2fa3
...
incubator nginx     40285d8a14f1ac5787e405e1023cf0c07f6aa28c
incubator nginx     58ea0ff91474d488ea50829042b45fe962bd2fa3 *
...
ksdev pkg install incubator/nginx
ksdev pkg list --installed
...
incubator nginx …
```

List environment-scoped packages in addition to globally-scoped packages

---

pkg/actions/pkg_list.go
pkg/actions/pkg_list_test.go
pkg/actions/testdata/pkg/list/installed.txt
pkg/actions/testdata/pkg/list/output.json
pkg/actions/testdata/pkg/list/output.txt
pkg/registry/mocks/PackageManager.go
pkg/registry/package_manager.go
pkg/registry/package_manager_test.go

Closes #626
```
ks init pkg-list && cd pkg-list
ks env add dev
ks env add stage
ks pkg install incubator/nginx@master
ks pkg install --env stage --force incubator/nginx@master
ks pkg install --env dev incubator/nginx@consistency
ks pkg install --env dev incubator/apache@master
ks pkg install --env stage --force incubator/apache@master
ks pkg list --installed
...
REGISTRY  NAME   VERSION                                  INSTALLED ENVIRONMENTS
========  ====   =======                                  ========= ============
incubator apache 40285d8a14f1ac5787e405e1023cf0c07f6aa28c *         dev, stage
incubator nginx  40285d8a14f1ac5787e405e1023cf0c07f6aa28c *         stage
incubator nginx  58ea0ff91474d488ea50829042b45fe962bd2fa3 *         dev …
```

Show environment scope in pkg list

---

pkg/actions/import.go
pkg/helm/renderer.go
pkg/util/yaml/yaml.go

Some helm charts return multiple Kubernetes objects. The YAML parsing libs we have only will take the first and silently ignore the rest. This change breaks the returns files up into multiple objects so everything is accounted for.

render helm templates with multiple objects

---

Dockerfile

This change:
* removes debugging data from binary
* adds a /tmp directory to the generated image
Signed-off-by: Bryan Liles <bryanliles@gmail.com>

Add /tmp to docker image

---

docs/docker-image-build.md

fix edit of docker docs to match adding /tmp volume to image
I accidentally missed pushing this to previous PR #754

fix docker docs to remove extraneous mount

---

pkg/cluster/apply.go
pkg/cluster/apply_test.go

It is necessary to update the resource version if retrying an update due to a conflict. Otherwise, the code retries with the same resource version and will get another 409 back from Kubernetes.
Fixes https://github.com/ksonnet/ksonnet/issues/650
Signed-off-by: Chris Marchbanks <csmarchbanks@gmail.com>

Get a new version of the object when retrying on conflict

---

pkg/prototype/flags.go
pkg/prototype/flags_test.go

When use _ks generate_
```
$ ks generate --help
...
Global Flags:
-v, --verbose count[=-1]   Increase verbosity. May be given multiple times.
```
if use _ks generate_ with _--verbose(or -v)_, we meet error msg
```
$ ks generate deployed-service guestbook-ui   \
--image gcr.io/heptio-images/ks-guestbook-demo:0.1  \
--type ClusterIP \
--verbose=-1
```
> unknown flag: --verbose
> Usage of prototype-flags:
>       --containerPort string   Container port for service to target. (default "80")
>       --image string           Container image to deploy
>       --module string          Component module
>       --name string            Name of the service and deployment resources
>       --replicas string        Number of replicas (default "1")
>       --servicePort string     Port for the service …

fix verbose error message in generate cli

---

pkg/app/app010.go
pkg/upgrade/testdata/app010_env_targets.yaml
pkg/upgrade/testdata/app020_env_targets.yaml
pkg/upgrade/upgrade010.go
pkg/upgrade/upgrade010_test.go

ks upgrade canonicalizes environment target separators (/ -> .)

---

pkg/component/component.go
pkg/component/delete.go
pkg/component/delete_test.go
pkg/component/jsonnet.go
pkg/component/manager.go
pkg/component/mocks/Component.go
pkg/component/module.go
pkg/component/module_test.go
pkg/component/testdata/delete-env-params-nested.libsonnet
pkg/component/testdata/delete/components/nested/guestbook-ui.jsonnet
pkg/component/testdata/delete/components/nested/params.libsonnet
pkg/component/testdata/delete/environments/default/params.libsonnet
pkg/component/yaml.go

Removes component in module with `ks component rm module.name`. The previous behavior did not respect the module name.
#795

Remove component in module with

---

pkg/cluster/apply.go
pkg/cluster/apply_test.go
pkg/cluster/client.go
pkg/cluster/client_test.go
pkg/cluster/cluster.go
pkg/cluster/delete.go
pkg/cluster/discovery.go
pkg/cluster/ksonnet_object.go
pkg/cluster/ksonnet_object_test.go
pkg/cluster/object.go
pkg/cluster/object_describer.go
pkg/cluster/object_describer_test.go
pkg/cluster/object_test.go
pkg/cluster/upsert.go
pkg/cluster/upsert_test.go
pkg/diff/diff.go
pkg/diff/diff_test.go

This PR allows ks diff to consider objects that are not part of the
"all" category, e.g. Ingress, Certificate.
Additionally, the cluster settings of the environment being diffed are
respected and override the current context when deciding where to
connect.
Fixes #803
Fixes #809

ks diff support for objects outside of the "all" category

---

pkg/actions/actions_test.go
pkg/actions/pkg_describe.go
pkg/actions/pkg_describe_test.go
pkg/actions/pkg_install.go
pkg/actions/pkg_remove.go
pkg/app/schema.go
pkg/pkg/helm.go
pkg/pkg/local.go
pkg/pkg/name.go
pkg/pkg/name_test.go
pkg/pkg/pkg.go
pkg/pkg/pkg_test.go
pkg/registry/cache.go
pkg/registry/gc.go
pkg/registry/gc_test.go
pkg/registry/mocks/PackageManager.go
pkg/registry/package_manager.go
pkg/registry/package_manager_test.go
pkg/util/test/test.go

Packages are candidates for removal when they are no longer referenced by either a specific environment or the global scope.
Closes #624

Garbage collection for vendored packages

---

pkg/helm/caching_client.go
pkg/helm/caching_client_test.go
pkg/registry/add.go
pkg/registry/add_test.go
pkg/registry/helm.go
pkg/registry/manager.go

Helm client caches chart configuration to avoid multiple back-to-back downloads

---

pkg/actions/import_test.go
pkg/clicmd/import.go
pkg/clicmd/import_test.go

Closes #807 
`ks import -f config.yaml` will use `--module /` by default

Changed default module for import to /

---

pkg/actions/import.go
pkg/actions/import_test.go
pkg/actions/testdata/import/my-service.json

This PR removes the extra `/` added because the default module is `/` since 0.11
Added test to hit the code path on https://github.com/ksonnet/ksonnet/blob/master/pkg/actions/import.go#L203

Fix sourcePath for imported json on root module

---

e2e/env_test.go
pkg/actions/env_targets.go
pkg/actions/env_targets_test.go
pkg/app/app.go
pkg/app/app_test.go
pkg/app/base_app.go
pkg/app/mocks/App.go
pkg/clicmd/env_targets.go
pkg/clicmd/env_targets_test.go
pkg/upgrade/upgrade010.go
pkg/upgrade/upgrade010_test.go

To bring them in line with env set and env add operations on override environments.
closes #857

Add `--override` to env targets cli

---

Gopkg.lock
Gopkg.toml
vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/paths.go

Incorporates ksonnet/ksonnet-lib#155
Fixes #883

Fix panic during ksonnet-lib generate - when parameters exist after body parameter in cluster OpenAPI spec

---

.travis.yml
pkg/registry/github.go
pkg/util/archive/tgz.go

Fix typeflag reads in tgz.go

---

.goreleaser.yml

closes: https://github.com/ksonnet/ksonnet/issues/885
Tested cross build with following go version:
```
go version go1.10.5 linux/amd64
```
Manually copy the binary to ppc64le and s390x machine, ks works fine.
* ppc64le
```
root@cfcp02:~/ks_0.13.1_linux_ppc64le# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
root@cfcp02:~/ks_0.13.1_linux_ppc64le# uname -a
Linux cfcp02 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:44:24 UTC 2017 ppc64le ppc64le ppc64le GNU/Linux
```
* s390x
```
root@platcon3:~/ks_0.13.1_linux_s390x# …
```

add ppc64le and s390x support

---

pkg/cluster/apply.go
pkg/cluster/ksonnet_object.go
pkg/cluster/ksonnet_object_test.go
pkg/cluster/merger.go
pkg/cluster/merger_test.go
pkg/cluster/upsert.go

Fixes #615
---
```
$ k create -f kuard.yaml
pod/kuard created
$ k get -o yaml pod/kuard | yq .metadata.labels
null
$ ks apply --dry-run default
INFO tagging ksonnet managed object (dry-run)
INFO upserting object (dry-run)
$ k get -o yaml pod/kuard | yq .metadata.labels
{
"ksonnet.io/component": "kuard"
}
```
```
$ k delete -f kuard.yaml
pod "kuard" deleted
$ k create -f kuard.yaml
pod/kuard created
$ k get -o yaml pod/kuard | yq .metadata.labels
null
$ ksdev apply --dry-run default
INFO tagging ksonnet managed object (dry-run)
INFO upserting object (dry-run)
$ k get -o yaml pod/kuard | yq .metadata.labels
null
```

Prevent resource patching when applying in dry-run mode
