ksonnet/ksonnet

- cmd/env.go
- cmd/root.go
- metadata/environment.go
- metadata/environment_test.go
- metadata/manager_test.go
- pkg/kubecfg/env.go
> Rename environment uri references to server

- prototype/specification.go
Currently we allow users to specify prototypes using Jsonnet. At the
head of each prototype should be a comment with semi-structured
metadata, e.g.,
```
// @apiVersion 0.0.1
// @name io.ksonnet.pkg.nginx-simple
// @description Deploys a simple, stateless nginx server with server
// blocks (roughly equivalent
//   to nginx virtual hosts). The nginx container is deployed using a
//   Kubernetes deployment, and is exposed to a network with a service.
// @param namespace string default Namespace in which to put the
// application
// @param name string Name to give to each of the components
```
Critically, some metadata about params is stored using the `@param` tag,
including name, type, and description, for pretty printing.
This commit will introduce a new param type, `@optionalParam`. This …
> Add optional params to prototype spec

- metadata/environment.go
- metadata/environment_test.go
Currently the env directory is being renamed on `env set foo
--name=bar`, however the `foo.jsonnet` file also needs to be renamed to
`bar.jsonnet`. This commit fixes that.
Fixes #54
> Renaming environment should also rename nested .jsonnet

- cmd/dep.go
- pkg/kubecfg/env.go
- pkg/kubecfg/param.go
- prototype/specification.go
- utils/strings.go
- utils/strings_test.go
Historically, every time we've needed to write out something tabular,
we've hand-rolled an ad hoc padded row writer. Yes, in each case. Such
is #startuplife.
The third time we did this we wrote this with bugs, and so now we are
rewriting it in a general, tested function, and transitioning all places
where we call this to use this function.
> 💅 Add row-padding string pretty printer

- cmd/root.go
> Gracefully handle error when kubeconfig not present

- README.md
cc @jessicayuen @hausdorff no rush, just some minor fixes
> [docs] Very minor README edits

- README.md
- docs/README.md
- docs/build-install.md
Signed-off-by: Joe Beda <joe.github@bedafamily.com>
> Document brew install

- metadata/params/params.go
- metadata/params/params_test.go
Fixes #45 
- Supports top-level imports for component params schema
- Support reading of multi-line jsonnet params
> Better support for jsonnet param schemas

- cmd/apply.go
- docs/cli-reference/ks.md
- docs/cli-reference/ks_apply.md
Primarily,
1. Emphasize on the new '-c' flag, removing '-f'.
2. Adding related commands
3. Clarifying the use cases for apply
> Update apply CLI docs

- README.md
- docs/README.md
- docs/concepts.md
Small changes, pretty self-explanatory, but feel free to disagree with any of these.
PTAL @jessicayuen thx!
> [doc] Updates/polish

- README.md
Small change for https://github.com/ksonnet/ksonnet/issues/185
Tested, these images work.
@jessicayuen PTAL thanks!
> [docs] Formalize container image names

- README.md
> [docs] Relax 1.8 req

- Makefile
> Update default version in Makefile to v0.7.0

- docs/README.md
- docs/troubleshooting.md
- metadata/registry_managers.go
> Implement github token to work around rate limits

- CONTRIBUTING.md
- Makefile
Reverts ksonnet/ksonnet#192
-- I will update homebrew to make with the correct version instead.
Fixes #198
> Revert "Update default version in Makefile to v0.7.0"

- docs/concepts.md
@hausdorff when you get a chance, PTAL? Thanks!
This is to address https://github.com/ksonnet/ksonnet/issues/208
> [docs] Fix premature claim of YAML support in components explanation

- CHANGELOG.md
> Prepare 0.8.0 release

- utils/meta.go
- utils/meta_test.go
proposal #236 
Signed-off-by: kyamazawa <yamazawa@supersoftware.co.jp>
> Supports k8s version number including symbols etc.

- README.md
Updated link per https://github.com/ksonnet/ksonnet/issues/256#issuecomment-354507514
Signed-off-by: Levi Blackstone <levi.blackstone@rackspace.com>
> Reference current Slack channel in README

- cmd/root.go
Fixes #251 
Signed-off-by: Levi Blackstone <levi.blackstone@rackspace.com>
> Handle case where KUBECONFIG is set without named context

- .github/ISSUE_TEMPLATE.md
Based on https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md
Signed-off-by: Levi Blackstone <levi.blackstone@rackspace.com>
> Create a GitHub issue template

- design/README.md
- design/proposals/fresh-clone.md
- design/proposals/ks-registry-update-delete.md
Signed-off-by: Alex Clemmer <clemmer.alexander@gmail.com>
> Design: propose improvements to the "fresh clone" story

- design/README.md
- design/proposals/explicit-environment-metadata.md
And format file to be consistent with other proposals.
> Add env. metadata proposal link to README

- design/proposals/ksonnet-lib-simple-constructors.md
Introduce simple constructors for ksonnet-lib, so it's easier to build
abstractions based on ksonnet-lib.
> design proposal: ksonnet lib simple constructors

- design/proposals/modular-components.md
Proposal to solve the problems mentioned in #292.
In summary:
* Introduce the concept of _targets_, easily allowing an environment to target specific components.
* Add optional hierarchy structure to components, for grouping and reusability.
* Allow environments to operate on multiple _destinations_.
* Consolidate shared environment metadata and configuration files.
> Proposal: Modular components and cleaner environments

- cmd/apply.go
- cmd/delete.go
- cmd/diff.go
- cmd/root.go
- cmd/show.go
- cmd/validate.go
- template/expander.go
- utils/acquire.go
- utils/openapi_test.go
Use afero when possible to allow for fs flexibitily (in tests or other instances).
fixes #39
> use afero when possible

- design/roadmap.md
> updating 1.0 roadmap

- generator/ksonnet.go
- generator/ksonnet_test.go
- metadata/clusterspec.go
- metadata/clusterspec_test.go
- metadata/environment.go
- metadata/interface.go
- metadata/manager.go
* Extracts ksonnet generator to a new package to make it easier to incorporate in new code. 
* Exports functions in `ClusterSpec` interface to make them available in more places.
> Extract ksonnet generator

- client/client.go
- cmd/apply.go
- cmd/delete.go
- cmd/diff.go
- cmd/env.go
- cmd/init.go
- cmd/root.go
- cmd/validate.go
- pkg/kubecfg/apply.go
- pkg/kubecfg/delete.go
- pkg/kubecfg/validate.go
> Pull client-go logic out of cmd/root.go and into client/ package

- metadata/environment.go
- metadata/lib/lib.go
- metadata/lib/lib_test.go
- metadata/manager_test.go
> Attempt to generate lib directory when not found

- CHANGELOG.md
> Create 0.9.0 version notes

- CHANGELOG.md
- metadata/manager.go
> Add #338 to changelog

- metadata/app/app.go
- metadata/app/app001.go
- metadata/app/app001_test.go
- metadata/app/app010.go
- metadata/app/app010_test.go
apiVersion 0.1.0 apps are not saving k8s version.
> save k8s version in 0.1.0 app

- CHANGELOG.md
> Add ChangeLog for v0.9.1

- cmd/root.go
> bug: env used incorrent params for rendering

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/catalog.go
- vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/extension.go
- vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/ksonnet/properties.go
- vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/nodemaker/nodemaker.go
> bug: mapContainer extension typo

- actions/prototype_list.go
- actions/prototype_list_test.go
- actions/testdata/prototype/list/output.txt
- cmd/prototype.go
- cmd/prototype_list.go
- e2e/prototype_test.go
- e2e/testdata/output/prototype/list/output-with-addition.txt
- pkg/pkg/pkg.go
> Update prototype list action

- cmd/env.go
- metadata/environment.go
- metadata/environment_test.go
- metadata/interface.go
- pkg/kubecfg/env.go
> bug: fix updating env namespace

- CHANGELOG.md
> releasing 0.9.2

- actions/init.go
- actions/init_test.go
- pkg/registry/manager_test.go
> removing need for github access for registry tests

- client/client.go
- client/client_test.go
- metadata/lib/clusterspec.go
> use provided tls configuration if possible when fetching api spec

- actions/init_test.go
- client/client.go
- cmd/actions.go
- cmd/env.go
- cmd/init.go
- cmd/init_test.go
- pkg/appinit/init_test.go
- pkg/kubecfg/validate.go
> introduce method to test cmd flags

- component/testdata/trailing-dash.yaml
- component/yaml.go
- component/yaml_test.go
> Handle YAML components which end with `--`

- e2e/testdata/output/init/gitignore
- pkg/appinit/init.go
> ignore app override by default

- e2e/apply_test.go
- e2e/param_test.go
- e2e/testdata/output/apply/output.txt
- pkg/env/data.go
- pkg/pipeline/pipeline.go
> generate env params with ext var to support modules

- actions/import.go
- actions/import_test.go
- cmd/import.go
- component/create.go
- docs/cli-reference/ks_import.md
> import component from a http URL

- actions/actions.go
- actions/env_list.go
- actions/env_list_test.go
- actions/testdata/env/list/output.json
- cmd/env.go
- cmd/env_list.go
- cmd/env_list_test.go
- docs/cli-reference/ks_env_list.md
- pkg/util/test/test.go
> Add JSON output to `env list`

- pkg/appinit/init.go
> add .ks_environment to generated gitignore

- actions/init.go
- actions/init_test.go
- actions/pkg_install_test.go
- actions/registry_add.go
- actions/registry_add_test.go
- actions/registry_list.go
- e2e/registry_test.go
- pkg/registry/add.go
- pkg/registry/add_test.go
- pkg/registry/cache.go
- pkg/registry/cache_test.go
- pkg/registry/fs.go
- pkg/registry/fs_test.go
- pkg/registry/github.go
- pkg/registry/github_test.go
- pkg/registry/manager.go
- pkg/registry/manager_test.go
- pkg/registry/mocks/Registry.go
- pkg/registry/registry.go
- pkg/schema/rice-box.go
FS registry should be able to handle relative paths
> FS registry can handle relative paths

- actions/prototype_preview.go
- actions/prototype_use.go
- cmd/prototype_preview.go
> Add help when generating or previewing prototypes

- actions/prototype_use.go
- e2e/generate_test.go
> Don't panic when runing `ks generate` with no args

- pkg/schema/properties.go
- pkg/schema/properties_test.go
- pkg/schema/testdata/deployment.yaml
> Support bool for object values in YAML

- pkg/util/jsonnet/object.go
> Handle null as a value

- CHANGELOG.md
> Fixed year 2017 -> 2018

- pkg/env/env.go
> evaluator is missing ksonnet vendor path

- pkg/registry/cache.go
- pkg/registry/cache_test.go
- pkg/registry/fs.go
- pkg/registry/fs_test.go
- pkg/registry/github.go
- pkg/registry/github_test.go
- pkg/registry/mocks/Registry.go
- pkg/registry/registry.go
> Generate proper vendor paths for gh registry with in root

- pkg/env/env.go
> Supply proper codes for building env jsonnet

- .travis.yml
> Cleaning up travis build

- e2e/testdata/output/component/rm/params-output.txt
- e2e/testdata/output/param/diff/output.txt
> Removing index columns from e2e tests

- Gopkg.lock
- Gopkg.toml
> updating ksonnet-lib to v0.1.0

- docs/overrides.md
> Adding initial override documentation

- CHANGELOG.md
> prepare changelog for v0.10.0

- Gopkg.lock
- Gopkg.toml
- pkg/pipeline/pipeline.go
- vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/printer/printer.go
> update ksonnet lib printer with array comprehensions

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/printer/printer.go
> updating ksonnet-lib to v0.1.3

- pkg/app/schema.go
> Omit library gitVersion if null

- pkg/cluster/apply.go
- pkg/cluster/object.go
- pkg/cluster/object_test.go
- utils/meta.go
> Label objects created by ksonnet

- docs/cli-reference/ks.md
- docs/cli-reference/ks_env.md
- docs/cli-reference/ks_env_add.md
- docs/cli-reference/ks_env_current.md
- docs/cli-reference/ks_env_describe.md
- docs/cli-reference/ks_env_list.md
- docs/cli-reference/ks_env_rm.md
- docs/cli-reference/ks_env_set.md
- docs/cli-reference/ks_env_targets.md
- docs/cli-reference/ks_env_update.md
- docs/cli-reference/ks_module.md
- docs/cli-reference/ks_module_create.md
- docs/cli-reference/ks_module_list.md
- pkg/app/app010.go
- pkg/appinit/init.go
- pkg/clicmd/env.go
- pkg/clicmd/env_add.go
- pkg/clicmd/env_add_test.go
- pkg/clicmd/env_describe.go
- pkg/clicmd/env_rm.go
- pkg/clicmd/env_targets.go
- pkg/clicmd/env_update.go
- pkg/clicmd/module.go
- pkg/clicmd/module_create.go
- pkg/clicmd/module_list.go
> Detect cluster version when adding an envirohnment

- CHANGELOG.md
> updating changelog for 0.11

- cmd/ks/main.go
- pkg/actions/diff.go
- pkg/actions/diff_test.go
- pkg/clicmd/root.go
- pkg/diff/diff.go
Ensure that diff creates an error and prints the output when changes
are detected.
> Add additional test coverage to diff

- Makefile
> Removing unused integrationtest task from Makefile

- pkg/actions/env_set.go
- pkg/actions/env_set_test.go
- pkg/app/app.go
- pkg/clicmd/env_set.go
- pkg/clicmd/env_set_test.go
- pkg/clicmd/flags.go
- pkg/env/create.go
adds --server flag to `ks env set` options
also also fixes a couple bugs and adds version to INFO log on init
> enable env set to change server

- pkg/appinit/init.go
- pkg/registry/cache.go
- pkg/registry/fs.go
- pkg/registry/fs_test.go
- pkg/registry/github.go
- pkg/registry/github_test.go
- pkg/registry/manager.go
also: rename registry.makePath -> regsitry.registrySpecFilePath
> fixes to CacheRoot, additional tests for GitHub registry.

- pkg/registry/add.go
- pkg/registry/fs.go
- pkg/registry/fs_test.go
- pkg/registry/github.go
- pkg/registry/github_test.go
- pkg/registry/helm.go
- pkg/registry/helm_test.go
- pkg/registry/mocks/Registry.go
- pkg/registry/registry.go
Fixes over-restrictive validation from #601
> Validate URI when adding registry

- docs/cli-reference/ks_registry_add.md
- pkg/actions/registry_add.go
- pkg/actions/registry_add_test.go
- pkg/clicmd/registry_add.go
- pkg/registry/add.go
- pkg/registry/add_test.go
> Remove defunct --version flag from registry add command

- pkg/actions/env_describe_test.go
- pkg/actions/env_list_test.go
- pkg/actions/env_set.go
- pkg/actions/env_set_test.go
- pkg/actions/env_targets_test.go
- pkg/actions/env_update_test.go
- pkg/actions/validate_test.go
- pkg/app/app.go
- pkg/app/app001.go
- pkg/app/app001_test.go
- pkg/app/app010.go
- pkg/app/app010_test.go
- pkg/app/base_app.go
- pkg/app/mocks/App.go
- pkg/app/override.go
- pkg/app/schema.go
- pkg/app/schema_test.go
- pkg/appinit/init.go
- pkg/component/delete.go
- pkg/component/delete_test.go
- pkg/diff/diff_test.go
- pkg/env/create.go
- pkg/env/create_test.go
- pkg/env/env_test.go
- pkg/env/rename_test.go
- pkg/env/util_test.go
- pkg/pipeline/pipeline_test.go
> Rename EnvironmentSpec[s] -> EnvironmentConfig[s]

- pkg/component/manager.go
- pkg/component/manager_test.go
> param set should understand module dot paths

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/printer/printer.go
* updates ksonnet-lib to 0.1.9 which solves issues with object field ids
Fixes #637
> Update ksonnet-lib to support conditionals in object keys

- Gopkg.lock
- Gopkg.toml
- pkg/component/yaml.go
- vendor/github.com/ksonnet/ksonnet-lib/ksonnet-gen/printer/printer.go
> Update ksonnet-lib printer to 0.1.10 to handle unescaping newlines

- pkg/app/base_app.go
> Remove verbose 'app called' debug messages

- docs/cli-reference/ks_env.md
- pkg/clicmd/env.go
Remove `.metadata` and `spec.json` from tree
> Update environment cli docs to remove old metadata cache structure

- pkg/util/strings/rand.go
- pkg/util/strings/rand_test.go
Adding more test cases to rand string gen. 
> Add more test cases to rand string gen

- pkg/pkg/local.go
- pkg/pkg/local_test.go
> Support prototype resolution from legacy unversioned package paths

- docs/cli-reference/ks_env_set.md
- pkg/clicmd/env_set.go
> Add examples for CLI ref --api-spec and --server for env set

- docs/docker-image-build.md
closes #748 
need to specify a netowrk to accomplish anything useful
> fix docker docs by adding net info

- CHANGELOG.md
> Update changelog for 0.12

- CHANGELOG.md
> Fix changelog links for 0.12.0-rc1

- docs/concepts.md
Update default k8s API to v1.8.0
> Remove metadata cache and env spec from concepts

- CHANGELOG.md
Draft for GoReleaser. This can be closed if included in the release.
> Update changelog from 0.12-rc1 to 0.12.0

- .goreleaser.yml
- Makefile
> Pass ldflags to goreleaser

- pkg/env/data.go
> update example with new syntax

- pkg/actions/registry_add_test.go
> Add test for GitHub enterprise URI detection

- pkg/registry/cache.go
- pkg/registry/github.go
- pkg/registry/github_test.go
> Allow reuse of installed packages in other scopes

- pkg/actions/pkg_install.go
- pkg/actions/pkg_install_test.go
Avoid orphaning vendored packages by validating environments prior to installation.
Closes #702
```
ks pkg install --env foo incubator/nginx
ERROR checking environment: environment "foo" was not found 👍
ks pkg install --env default incubator/nginx
INFO Retrieved 7 files
ks pkg install incubator/nginx
```
> Validate environment prior to fetching package

- e2e/testdata/output/version/default.txt
- pkg/pipeline/pipeline.go
to match shipping version, and remove errant print that was breaking
param list tests
Signed-off-by: Derek Wilson <derek@heptio.com>
> update expected jsonnet version and fix e2e tests

- design/roadmap.md
> updating roadmap as of 9/5

- pkg/actions/actions.go
- pkg/app/app.go
- pkg/app/base_app.go
- pkg/app/override.go
- pkg/app/override030.go
- pkg/upgrade/upgrade010.go
> Handle override upgrades

- pkg/cluster/sort.go
- pkg/cluster/sort_test.go
- pkg/diff/diff_test.go
> Sort resources semantically to tighten up reconciliation

- CHANGELOG.md
Update changelog on repo to be pulled onto website
> Update change log to 0.13

- pkg/cluster/delete.go
- pkg/cluster/merger.go
- pkg/component/create.go
- pkg/diff/location.go
- pkg/params/lister.go
- pkg/prototype/interface.go
- pkg/prototype/jsonnet_parser.go
With this PR I try to fix various string formatting warnings. Please look my changes over and let me know if I've done anything wrong!
> Fix string formatting

- CHANGELOG.md
> Update changelog in preparation for 0.13.1

- docs/build-install.md
Fix #897
Signed-off-by: Xiang Dai <764524258@qq.com>
> docs/build-install.md: state go version
